import type { DocumentTemplateDefinition } from "./contracts";

const AI_RESPONSIBILITIES = [
  "title_content",
  "subtitle_decision",
  "abstract_content",
  "keyword_selection",
  "section_names",
  "section_order",
  "section_count",
  "section_content",
  "section_length",
  "paragraph_organization",
  "transitions",
  "terminology_consistency",
  "abbreviation_definition",
  "redundancy_reduction",
  "logical_order",
  "discussion_decision",
  "limitations_decision",
  "future_perspective_decision",
  "conclusion_content",
  "figure_need",
  "figure_type",
  "figure_content",
  "figure_caption",
  "figure_placement",
  "table_need",
  "table_content",
  "table_caption",
  "table_placement",
  "citation_placement",
  "citation_mapping",
  "figure_cross_reference",
  "table_cross_reference",
  "reference_order",
  "language_polish",
  "sentence_variety",
  "academic_tone",
  "content_completeness",
  "context_consistency",
  "figure_text_consistency",
  "reference_consistency",
] as const;

export const SCI_REVIEW_TEMPLATE: DocumentTemplateDefinition = {
  templateId: "sci-review",
  templateVersion: "2",
  status: "active",
  displayName: "SCI Review Word",
  description:
    "Single-column SCI-style review manuscript with abstract, keywords, structured sections, figures, tables, and verified numeric references.",
  documentType: "sci_review",
  supportedLanguages: ["zh", "en"],
  supportedFormats: ["docx"],
  matchProfile: {
    suitableFor: [
      "SCI or Nature-style literature reviews",
      "academic review manuscripts",
      "scientific Word documents requiring abstract and references",
    ],
    unsuitableFor: [
      "business proposals",
      "presentation decks",
      "spreadsheets",
      "casual essays without academic structure",
    ],
  },
  componentBlueprints: [
    {
      componentKey: "title",
      type: "title",
      required: true,
      repeatable: false,
      minimumCount: 1,
      maximumCount: 1,
      purpose: "Generate the final scientific document title.",
    },
    {
      componentKey: "abstract",
      type: "abstract",
      required: true,
      repeatable: false,
      minimumCount: 1,
      maximumCount: 1,
      purpose: "Generate one mature abstract from the completed document.",
    },
    {
      componentKey: "keywords",
      type: "keywords",
      required: true,
      repeatable: false,
      minimumCount: 1,
      maximumCount: 1,
      purpose: "Select three to eight final keywords.",
    },
    {
      componentKey: "section",
      type: "section",
      required: true,
      repeatable: true,
      minimumCount: 1,
      maximumCount: 8,
      purpose:
        "Generate ordered mature sections, including headings, paragraphs, tables, and figure requests when supported.",
    },
    {
      componentKey: "conclusion",
      type: "conclusion",
      required: true,
      repeatable: false,
      minimumCount: 1,
      maximumCount: 1,
      purpose: "Generate the final conclusion and justified outlook.",
    },
    {
      componentKey: "references",
      type: "reference_list",
      required: true,
      repeatable: false,
      minimumCount: 1,
      maximumCount: 1,
      purpose:
        "Select only verified references used by the approved document content.",
    },
  ],
  aiResponsibilities: [...AI_RESPONSIBILITIES],
  fixedRulesDocument: "docs/templates/sci-review-v1.md",
  snapshotSeed: {
    templateId: "sci-review",
    templateVersion: "2",
    origin: { kind: "system" },
    renderingProfile: "sci_word_v1",
    contentProfile: "sci_review_v1",
    typography: {
      titleStyle: "DocumentTitle",
      heading1Style: "Heading1",
      heading2Style: "Heading2",
      heading3Style: "Heading3",
      bodyStyle: "Body",
      captionStyle: "Caption",
      referenceStyle: "Reference",
    },
    layout: {
      pageSize: "A4",
      orientation: "portrait",
      columns: 1,
    },
    rules: {
      headingDepth: 3,
      figureCaptionPosition: "below",
      tableCaptionPosition: "above",
    },
    citationPolicy: {
      policyVersion: "sci-citation-v1",
      placement: "before_terminal_punctuation",
      display: "bracketed",
      includeAbstract: false,
      includeFigureCaptions: false,
      includeTableCaptions: false,
      includeAppendices: true,
    },
  },
};
