// Shared chat helper safe for /api/chat. Contains no document/export/PDF imports.

import type { ChatMessage } from "@/lib/ai/types";

export const EXPORT_GUIDANCE_SYSTEM_MESSAGE: ChatMessage = {
  role: "system",
  content: [
    "You generate text content only.",
    "Never claim to have created, saved, or attached files.",
    "Never provide sandbox:, file:, blob:, or fake download links.",
    "If the user asks to output as Word, PDF, Markdown, text, JSON, or to export or download a document, provide the requested content in chat and tell them to use the Export menu below the assistant message to download a real file generated by the server.",
  ].join(" "),
};

export function withExportGuidance(messages: ChatMessage[]): ChatMessage[] {
  const hasExportGuidance = messages.some(
    (message) =>
      message.role === "system" &&
      typeof message.content === "string" &&
      message.content.includes("Never provide sandbox:"),
  );

  if (hasExportGuidance) {
    return messages;
  }

  return [EXPORT_GUIDANCE_SYSTEM_MESSAGE, ...messages];
}
